name: build-feed

on:
  schedule:
    - cron: '50 5 * * *'   # daily at 05:50 UTC
  workflow_dispatch:       # manual run
  push:
    paths:
      - 'scripts/**'
      - 'docs/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/build-feed.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build feed (24h / 12 items)
        run: node scripts/buildFeed.mjs

      - name: Ensure docs folder exists
        run: mkdir -p docs

      - name: Commit docs if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/playlist.json
          git diff --cached --quiet || git commit -m "pages: publish feed (24h/12 items)"

      - name: Push back to main
        run: git push origin HEAD:main