name: newsletter

on:
  schedule:
    - cron: '0 6 * * *'           # every day at 06:00 UTC
  workflow_dispatch:               # allow manual test runs

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build feed
        run: node scripts/buildFeed.mjs

      - name: Debug feed output
        run: |
          node -e "const f=require('fs');const a=JSON.parse(f.readFileSync('docs/playlist.json','utf8'));console.log('COUNT',a.length);console.log('FIRST',a[0]||{})"

      # Send as a Brevo campaign (robust + visível no painel)
      - name: Send daily digest via Brevo (campaign to list)
        env:
          BREVO_API_KEY:       ${{ secrets.BREVO_API_KEY }}
          BREVO_LIST_ID:       ${{ secrets.BREVO_LIST_ID }}        # deve ser "3"
          BREVO_SENDER_EMAIL:  ${{ secrets.SENDER_EMAIL }}         # podes mapear dos teus secrets atuais
          BREVO_SENDER_NAME:   ${{ secrets.SENDER_NAME }}
        run: node scripts/sendBrevo.mjs